services:
  - type: web
    name: aeroforecast
    env: node
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    plan: free
    regions: [oregon]
    runtime: node
    nodeVersion: 18.17.0
    buildFilter:
      paths:
        - client/**/*
        - server/**/*
        - shared/**/*
        - package.json
        - vite.config.ts
        - tsconfig.json
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
